
defaults:

    wandb_key: '143ab19b3eb2d5d944a3df9ab5f408fda52bd963'
    id: 'Renyi-v0'
    project: 'RB'
    userid: 'vilmarith2'
    univariate_sim: False
    multivariate_sim: False
    mab_sim: False
    arms: 3
    
    x_: 20
    x_max: 1.1
    sl_factor: 1
    y_factor: 0.4
    sp_factor: 1
    sq: 0.0001
    mu_q: 1
    bp: 0.8
    bl: 0.8
    al: 0.8
    ap: 0.8
    lp: 0.8
    ll: 0.01
    plot: False
    
    learning_rate: 0.1
    bound: 'Renyi'
    alpha: 0.9999
    num_iters: 10
    prior_q: 25
    sigma_q: 1.0
    prior_mu1: [13, 16, 10]
    prior_sigma1: [1.5, 1.5, 1.5]
    prior_mu2: [20, 14, 17]
    prior_sigma2: [1.5, 1.5, 1.5]
    mixture_weight_prior: [0.5, 0.5, 0.5]
    gen_proc_mode1: [10, 16, 18]
    gen_proc_mode2: [22, 16, 10]
    gen_proc_std1: [1, 3, 1]
    gen_proc_std2: [1, 3, 1]
    mixture_weight_gen_proc: [0.97, 1.0, 0.97]
    num_obs: 1000
    mc_samples: 1000
    save_distributions: True
    train: False
    run: 1
    log_every: 100
    num_updates: 10
    log_reg_every: 100
    print_log: True
    generate_contour: True
    means_min: 7.0
    means_max: 25.0
    means_step: 0.2
    
    sigmas_min: 0.5
    sigmas_max: 3.5
    sigmas_step: 0.1
       
unisim:

    univariate_sim: True
    x_: 20
    x_max: 1.1
    sl_factor: 1
    y_factor: 0.4
    sp_factor: 1
    sq: 0.0001
    mu_q: 1
    bp: 0.8
    bl: 0.8
    al: 0.8
    ap: 0.8
    lp: 0.8
    ll: 0.01
    plot: False
    
multisim:

    multivariate_sim: True
    learning_rate: 0.1
    bound: 'Renyi'
    alpha: 9999999999 #1e9
    num_iters: 10000
    prior_q: 25
    sigma_q: 1.0
    prior_mu1: [13, 16, 10]
    prior_sigma1: [1.5, 1.5, 1.5]
    prior_mu2: [20, 14, 17]
    prior_sigma2: [1.5, 1.5, 1.5]
    mixture_weight_prior: [0.5, 0.5, 0.5]
    gen_proc_mode1: [10, 16, 18]
    gen_proc_mode2: [22, 16, 10]
    gen_proc_std1: [1, 3, 1]
    gen_proc_std2: [1, 3, 1]
    mixture_weight_gen_proc: [0.97, 1.0, 0.97]
    num_obs: 1000
    mc_samples: 1000
    save_distributions: True
    train: False
    run: 1
    log_every: 100
    num_updates: 10
    log_reg_every: 100
    print_log: True
    generate_contour: True
    means_min: 7.0
    means_max: 25.0
    means_step: 0.2
    
    sigmas_min: 0.5
    sigmas_max: 3.5
    sigmas_step: 0.1
    
mabsim:

    mab_sim: True
    learning_rate: 0.05 # 2e-2
    alpha: 1000000000.0
    num_iters: 5000
    prior_q: 25
    sigma_q: 0.0000008 #1e-8
    prior_mu1: [13, 16, 10]
    prior_sigma1: [1.5, 1.5, 1.5]
    prior_mu2: [20, 14, 17]
    prior_sigma2: [1.5, 1.5, 1.5]
    mixture_weight_prior: [0.5, 0.5, 0.5]
    gen_proc_mode1: [10, 16, 18]
    gen_proc_mode2: [22, 16, 10]
    gen_proc_std1: [1, 3, 1]
    gen_proc_std2: [1, 3, 1]
    mixture_weight_gen_proc: [0.97, 1.0, 0.97]
    num_obs: 1000
    mc_samples: 300
    save_distributions: False
    train: True
    run: 1
    log_every: 50
    num_updates: 10
    log_reg_every: 50
    generate_contour: False
    